name       : easyssh
version    : 1.7.7
release    : 24
source     :
    - https://github.com/muriloventuroso/easyssh/archive/1.7.7.tar.gz : a43565bbc0e1c3796e393ee464bfc5360f09ffee0ed6952f14010d181bfa7c07
license    : GPL-3.0-or-later
component  : network.util
summary    : A complete, efficient and easy-to-use ssh manager. Create and edit connections, groups, customize the terminal, with multiple instances of the same connection
description: |
    A complete, efficient and easy-to-use ssh manager. Create and edit connections, groups, customize the terminal, with multiple instances of the same connection.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(glib-2.0)
    - pkgconfig(gpgme)
    - pkgconfig(granite)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(vte-2.91)
    - vala
rundeps    :
    - gpgme
setup      : |
    %meson_configure -Dwith-gpg=true \
                     -Dpatched-vte=true \
                     -Dubuntu-bionic-patched-vte=false
build      : |
    %ninja_build
install    : |
    %ninja_install
