name       : easyssh
version    : 1.6.1
release    : 15
source     :
    - https://github.com/muriloventuroso/easyssh/archive/1.6.1.tar.gz : 2a84f3c117e4af37667689150df8a7010cb838959843231a368d97ab8550afb0
license    : GPL-3.0-or-later
component  : network.util
summary    : A complete, efficient and easy-to-use ssh manager. Create and edit connections, groups, customize the terminal, with multiple instances of the same connection.
description: |
    A complete, efficient and easy-to-use ssh manager. Create and edit connections, groups, customize the terminal, with multiple instances of the same connection.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(glib-2.0)
    - pkgconfig(granite)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(vte-2.91)
    - gpgme-devel
    - vala
rundeps    :
    - gpgme
setup      : |
    %meson_configure -Dwith-gpg=true \
                     -Dlibunity=false \
                     -Dubuntu-bionic-patched-vte=false
build      : |
    %ninja_build
install    : |
    %ninja_install
