name       : easyssh
version    : 1.3.2
release    : 3
source     :
    - https://github.com/muriloventuroso/easyssh/archive/1.3.2.tar.gz : 504f58d27948cae78ad2113526ef0493e4f9d5249ef66e1deec06943bcc9b2d6
license    : GPL-3.0-or-later
component  : network.util
summary    : A complete, efficient and easy-to-use ssh manager. Create and edit connections, groups, customize the terminal, with multiple instances of the same connection.
description: |
    A complete, efficient and easy-to-use ssh manager. Create and edit connections, groups, customize the terminal, with multiple instances of the same connection.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(granite)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(vte-2.91)
    - vala
setup      : |
    %meson_configure -Dlibunity=false -Dubuntu-bionic-patched-vte=false
build      : |
    %ninja_build
install    : |
    %ninja_install
