name       : easyssh
version    : 1.6.6
release    : 20
source     :
    - https://github.com/muriloventuroso/easyssh/archive/1.6.6.tar.gz : 9ca938b62c4adf2fe23e4b855b55fbc61297515434d1a042155efdb4ec60a371
license    : GPL-3.0-or-later
component  : network.util
summary    : A complete, efficient and easy-to-use ssh manager. Create and edit connections, groups, customize the terminal, with multiple instances of the same connection
description: |
    A complete, efficient and easy-to-use ssh manager. Create and edit connections, groups, customize the terminal, with multiple instances of the same connection.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(glib-2.0)
    - pkgconfig(granite)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(vte-2.91)
    - gpgme-devel
    - vala
rundeps    :
    - gpgme
setup      : |
    %patch -p1 < $pkgfiles/utf8.patch
    %meson_configure -Dwith-gpg=true \
                     -Dlibunity=false \
                     -Dubuntu-bionic-patched-vte=false
build      : |
    %ninja_build
install    : |
    %ninja_install
