name       : easyssh
version    : 1.2.10
release    : 1
source     :
    - https://github.com/muriloventuroso/easyssh/archive/1.2.10.tar.gz : 6072ed7cf6a798c0d3b05b359a157f5d9e99a25faa6675f2c5be900db51a6c1c
license    : GPL-3.0-or-later 
component  : network.util
summary    : A complete, efficient and easy-to-use ssh manager. Create and edit connections, groups, customize the terminal, with multiple instances of the same connection.
description: |
    A complete, efficient and easy-to-use ssh manager. Create and edit connections, groups, customize the terminal, with multiple instances of the same connection.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(granite)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(vte-2.91)
    - vala
setup      : |
    %patch -p1 < $pkgfiles/unity.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
