name       : easyssh
version    : 1.4.6
release    : 9
source     :
    - https://github.com/muriloventuroso/easyssh/archive/1.4.6.tar.gz : 1d55291af3987ab4a4db1fc3c92cd555defa7a969eb47398bc373d35ab37d7dc
license    : GPL-3.0-or-later
component  : network.util
summary    : A complete, efficient and easy-to-use ssh manager. Create and edit connections, groups, customize the terminal, with multiple instances of the same connection.
description: |
    A complete, efficient and easy-to-use ssh manager. Create and edit connections, groups, customize the terminal, with multiple instances of the same connection.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(granite)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(vte-2.91)
    - gpgme-devel
    - vala
rundeps    :
    - gpgme
setup      : |
    %meson_configure -Dwith-pgp=true \
                     -Dlibunity=false \
                     -Dubuntu-bionic-patched-vte=false
build      : |
    %ninja_build
install    : |
    %ninja_install
